apiVersion: v1
kind: Service
metadata:
  name: {{ include "ubooquity.fullname" . }}
  labels:
{{ include "ubooquity.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 2202
      targetPort: http
      protocol: TCP
      name: http
    - port: 2203
      targetPort: http-admin
      protocol: TCP
      name: http-admin
  selector:
    app.kubernetes.io/name: {{ include "ubooquity.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
